# Generated by Django 3.2.9 on 2021-11-13 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('code', models.CharField(max_length=36, verbose_name='código')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player', verbose_name='administrador')),
                ('players', models.ManyToManyField(related_name='groups', to='players.Player', verbose_name='jogadores')),
            ],
        ),
    ]
