# Generated by Django 3.2.9 on 2021-11-14 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'grupo de jogadores', 'verbose_name_plural': 'grupos de jogadores'},
        ),
    ]
