# Generated by Django 3.2.9 on 2021-11-14 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_alter_player_options'),
        ('groups', '0003_alter_group_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='data e hora')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='grupo')),
                ('players', models.ManyToManyField(related_name='games', to='players.Player', verbose_name='jogadores')),
            ],
            options={
                'verbose_name': 'jogo',
                'verbose_name_plural': 'jogos',
            },
        ),
    ]
