# Generated by Django 3.2.9 on 2021-11-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='local',
            field=models.CharField(default='', max_length=255, verbose_name='local da partida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(default=10, verbose_name='quantidade máxima de jogadores'),
            preserve_default=False,
        ),
    ]
