# Generated by Django 3.2.9 on 2021-11-14 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'jogador', 'verbose_name_plural': 'jogadores'},
        ),
    ]
